[package]
name = "rapid"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rapid-svc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.9"
dotenvy = "0.15.7"
futures-util = "0.3"
magic = "0.16.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.18"
tokio = { version = "1.52.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
tower-http = { version = "0.6.6", features = ["cors", "fs", "trace", "limit"] }
uuid = { version = "1", features = ["v4"] }
aws-sdk-s3 = "1.131.0"
